name: Format Single Pkg Workflow

on:
  push:
    branches: 
      - develop
    paths-ignore:
      - 'docs/**'
      - '.github/**'
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:

  build_single_pkg:
    name: format single pkg
    uses: Mu2e/.github/.github/workflows/mu2e-format-single-pkg.yml@stable
    with:
      against-ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || github.event_name == 'push' && github.event.before || 0 }}
